const CLEAR = "CLEAR";

const CHANGE_FORM = "CHANGE_FORM";
const CHANGE_ADDRESS_PAGE = "CHANGE_ADDRESS_PAGE";
const CHANGE_ADDRESS_ROWS_PER_PAGE = "CHANGE_ADDRESS_ROWS_PER_PAGE";

export default {
    CLEAR,

    CHANGE_FORM,
    CHANGE_ADDRESS_PAGE,
    CHANGE_ADDRESS_ROWS_PER_PAGE
}