const GET_KEYS = "GET_KEYS";
const SET_KEYS = "SET_KEYS";
const CREATE_KEY = "CREATE_KEY";
const ADD_KEY = "ADD_KEY";

const SET_ASSETS = "SET_ASSETS";

const CHANGE_KEYS_PAGE = "CHANGE_KEYS_PAGE";
const CHANGE_KEYS_ROWS_PER_PAGE = "CHANGE_KEYS_ROWS_PER_PAGE";

const CHANGE_ASSETS_PAGE = "CHANGE_ASSETS_PAGE";
const CHANGE_ASSETS_ROWS_PER_PAGE = "CHANGE_ASSETS_ROWS_PER_PAGE";

const GET_STATE = "GET_STATE";

const SUBMIT_UPDATE = "SUBMIT_UPDATE";

const GET_ASSET = "GET_ASSET";
const SET_ASSET = "SET_ASSET";

export default {
    GET_KEYS,
    SET_KEYS,
    CREATE_KEY,
    ADD_KEY,

    SET_ASSETS,

    CHANGE_KEYS_PAGE,
    CHANGE_KEYS_ROWS_PER_PAGE,

    CHANGE_ASSETS_PAGE,
    CHANGE_ASSETS_ROWS_PER_PAGE,

    GET_STATE,

    SUBMIT_UPDATE,

    GET_ASSET,
    SET_ASSET
}